name: "deploy-site-to-production"
description: "Deploys the static site to Production"

inputs:
  site-name:
    required: true
  s3-bucket-name:
    required: true
  s3-public-objects:
    required: false
  data-stack-name:
    required: true
  service-stack-suffix:
    required: false
  distribution-id-export-name-suffix:
    required: true
  distribution-id-export-full-name:
    required: false
  contentful-space-id:
    required: true
  contentful-access-token:
    required: true

runs:
  using: "composite"
  steps:

  - name: PRODUCTION | PRD ACCOUNT | Build & Upload Gatsby site to S3 bucket
    uses: dearhealth/shared-workflows/.github/actions/static-sites/gatsby-contentful-build-and-deploy-data-stack@main
    with:
      site-name: ${{ inputs.site-name }}
      stage: production
      code-artifacts-domain: dh-artifacts
      code-artifacts-aws-account-id: 915964404932
      code-artifacts-aws-region: us-east-1
      region: eu-west-1
      role-to-assume: arn:aws:iam::580448008933:role/dh-github-role-Role-987BLSFWAVPU
      cfn-role: arn:aws:iam::580448008933:role/dh-cloudformation-role
      data-stack-name: ${{ inputs.data-stack-name }}
      s3-bucket-name: ${{ inputs.s3-bucket-name }}
      s3-public-objects: ${{ inputs.s3-public-objects }}
      contentful-space-id: ${{ inputs.contentful-space-id }}
      contentful-access-token: ${{ inputs.contentful-access-token }}

  - name: PRODUCTION | PRD ACCOUNT | Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      role-to-assume: arn:aws:iam::580448008933:role/dh-github-role-Role-987BLSFWAVPU
      aws-region: us-east-1
      role-session-name: prd-deployment

  - name: PRODUCTION | PRD ACCOUNT | prd deployment | Deploy Cloudformation SERVICE Stack (if present)
    uses: dearhealth/shared-workflows/.github/actions/static-sites/deploy-service-stack@main
    with:
      region: us-east-1
      cfn-role: arn:aws:iam::580448008933:role/dh-cloudformation-role
      service-stack-suffix: ${{ inputs.service-stack-suffix }}
      env: prd
      distribution-id-export-name-suffix: ${{ inputs.distribution-id-export-name-suffix }}
      distribution-id-export-full-name: ${{ inputs.distribution-id-export-full-name }}

  - name: PRODUCTION | PRD ACCOUNT | prd deployment | Deploy Cloudformation SERVICE Stack (if present)
    uses: dearhealth/shared-workflows/.github/actions/static-sites/deploy-service-stack@main
    with:
      region: eu-west-1
      cfn-role: arn:aws:iam::580448008933:role/dh-cloudformation-role
      service-stack-suffix: ${{ inputs.service-stack-suffix }}
      env: prd
      distribution-id-export-name-suffix: ${{ inputs.distribution-id-export-name-suffix }}
      distribution-id-export-full-name: ${{ inputs.distribution-id-export-full-name }}
