name: "run-serverless-ci"
description: "Runs poetry install and runs the pytest"

inputs:
  env:
    required: true
  region:
    required: true
  role-to-assume:
    required: true
    description: "Runs poetry install and runs the pytest"
  aws-account-id:
    required: true

runs:
  using: "composite"
  steps:
   - name: checkout
     uses: actions/checkout@v2
   - name: Start DynamoDB in GitHub Actions
     uses: rrainn/dynamodb-action@v2.0.1
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
        role-to-assume: ${{inputs.role-to-assume}}
        aws-region: ${{inputs.region}}
   - name: Download a single artifact
     uses: actions/download-artifact@v2
     with:
      name: packages-artifact
   - run: tar xvf packages.tar
     shell: bash
   - uses: actions/setup-node@v2
     with:
        node-version: '14'    
        cache: 'npm'
   - run: npm install
     shell: bash
   - run: npm install -g serverless@2
     shell: bash
   - run: sls deploy --stage ${{inputs.env}} --region ${{inputs.region}} --deploymentBucketName dh-deployment-bucket-${{inputs.aws-account-id}} --package dh-packages/${{inputs.env}}-${{inputs.region}}-build
     shell: bash
