name: "run-serverless-ci"
description: "Runs poetry install and runs the pytest"

inputs:
  env:
    required: true
  old-env-id:
    required: true
  region:
    required: true
  role-to-assume:
    required: true
    description: "Runs poetry install and runs the pytest"
  aws-account-id:
    required: true
  dh-artifacts-aws-account-id:
    required: true

runs:
  using: "composite"
  steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Amsterdam"
        timezoneMacos: "Europe/Amsterdam"
        timezoneWindows: "W. Europe Standard Time"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{inputs.role-to-assume}}
        aws-region: ${{inputs.region}}
    
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: packages-artifact

    - run: tar xvf packages.tar
      shell: bash

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: npm install deps
      run: |
        aws codeartifact login --tool npm --repository npm-store --domain dh-artifacts --region us-east-1 --domain-owner ${{inputs.dh-artifacts-aws-account-id}}
        npm install -g serverless@2
        npm install
      shell: bash

    - run: sls deploy --stage ${{inputs.env}} --region ${{inputs.region}} --deploymentBucketName dh-deployment-bucket-${{inputs.region}}-${{inputs.aws-account-id}} --aws-target-account-id ${{inputs.aws-account-id}} --old-env-id ${{inputs.old-env-id}} --package dh-packages/${{inputs.env}}-${{inputs.region}}-build
      shell: bash
