name: "deploy-site-on-staging"
description: "Deploys the static site on Staging"

inputs:
  s3-bucket-name:
    required: true
  data-stack-name:
    required: true
  service-stack-suffix:
    required: false
  distribution-id-export-name-suffix:
    required: true

runs:
  using: "composite"
  steps:
  - name: STAGING  DEV ACCOUNT Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      role-to-assume: arn:aws:iam::915964404932:role/dh-github-role-Role-Q04O78VX01NM
      aws-region: us-east-1

  # - uses: dearhealth/shared-workflows/.github/actions/static-sites/gatsby-contentful-build-data-and-deploy-data-stack@main
  - name: [STAGING | DEV ACCOUNT] Build & Upload Gatsby site to S3 bucket
    uses: ./.github/actions/static-sites/gatsby-contentful-build-data-and-deploy-data-stack@main
    with:
      cfn-role: arn:aws:iam::915964404932:role/dh-cloudformation-role
      data-stack-name: ${{ inputs.data-stack-name }}
      s3-bucket-name: ${{ inputs.s3-bucket-name }}
      contentful-space-id: ${{ secrets.CONTENTFUL_SPACE_ID }}
      contentful-access-token: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
    
  - name: [STAGING | DEV ACCOUNT | dev deployment] Deploy Cloudformation SERVICE Stack (if present)
    uses: ./.github/actions/static-sites/deploy-service-stack@main
    with:
      region: us-east-1
      cfn-role: arn:aws:iam::915964404932:role/dh-cloudformation-role
      service-stack-suffix: ${{ inputs.service-stack-suffix }}
      env: dev
      distribution-id-export-name-suffix: ${{ inputs.distribution-id-export-name-suffix }}

  - name: [STAGING | DEV ACCOUNT | tst deployment] Deploy Cloudformation SERVICE Stack (if present)
    uses: ./.github/actions/static-sites/deploy-service-stack@main
    with:
      region: us-east-1
      cfn-role: arn:aws:iam::915964404932:role/dh-cloudformation-role
      service-stack-suffix: ${{ inputs.service-stack-suffix }}
      env: tst
      distribution-id-export-name-suffix: ${{ inputs.distribution-id-export-name-suffix }}

  - name: [STAGING | PRD ACCOUNT] Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      role-to-assume: arn:aws:iam::580448008933:role/dh-github-role-Role-Q04O78VX01NM
      aws-region: us-east-1

  - name: [STAGING | PRD ACCOUNT | acc | us-east-1 deployment] Deploy Cloudformation SERVICE Stack (if present)
    uses: ./.github/actions/static-sites/deploy-service-stack@main
    with:
      region: us-east-1
      cfn-role: arn:aws:iam::580448008933:role/dh-cloudformation-role
      service-stack-suffix: ${{ inputs.service-stack-suffix }}
      env: acc
      distribution-id-export-name-suffix: ${{ inputs.distribution-id-export-name-suffix }}

  - name: [STAGING | PRD ACCOUNT | acc | eu-west-1 deployment] Deploy Cloudformation SERVICE Stack (if present)
    uses: ./.github/actions/static-sites/deploy-service-stack@main
    with:
      region: eu-west-1
      cfn-role: arn:aws:iam::580448008933:role/dh-cloudformation-role
      service-stack-suffix: ${{ inputs.service-stack-suffix }}
      env: acc
      distribution-id-export-name-suffix: ${{ inputs.distribution-id-export-name-suffix }}
