name: "run-serverless-ci"
description: "Runs poetry install and runs the pytest"

inputs:
  code-artifact-account:
    required: true
  code-artifact-domain:
    required: true
  role-to-assume:
    required: true
  aws-account-dev:
    required: true
  aws-account-tst:
    required: true
  aws-account-acc:
    required: true
  aws-account-prd:
    required: true

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1.1.0
      with:
        format: "YYYY_MM_DD"

    # - uses: rrainn/dynamodb-action@v2.0.1

    - uses: Gr1N/setup-poetry@v7

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{inputs.role-to-assume}}
        aws-region: us-east-1

    - run: |
        export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain  ${{inputs.code-artifact-domain}} --domain-owner ${{inputs.code-artifact-account}} --query authorizationToken --output text)
        poetry config http-basic.dh_repo aws "${CODEARTIFACT_AUTH_TOKEN}"
      shell: bash

    - uses: actions/cache@v2
      with:
        path: |
          .venv
#           poetry.lock
        key: ${{ steps.date.outputs.time }}-${{hashFiles('pyproject.toml')}}

    - uses: actions/cache@v2
      with:
        path: |
          ~/cache
        key: depcache

    - uses: actions/setup-node@v2
      with:
        node-version: '16'    
        cache: 'npm'

    - uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Configure python aliases & poetry
      run: |
        poetry install
        poetry env info
        python -m pip help install
        echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
        python3.8 -m pip help install
      shell: bash

    - name: Run tests
      run: |
        if test -f "pytest.ini"; then
          sed -i '/    LOCAL_DYNAMODB_ENDPOINT/s/=.*$/=http:\/\/dynamodb:8000/' pytest.ini
        fi
        poetry run pytest
      shell: bash

    - name: npm install deps
      run: |
        aws codeartifact login --tool npm --repository npm-store --domain dh-artifacts --region us-east-1 --domain-owner ${{inputs.aws-account-dev}}
        npm install -g serverless@2
        npm install
      shell: bash

    - run: mkdir dh-packages
      shell: bash

    - run: |
        sls package --stage dev --region us-east-1 --deploymentBucketName dh-deployment-bucket-us-east-1-${{inputs.aws-account-dev}} --aws-target-account-id ${{inputs.aws-account-dev}} --old-env-id develop --package dh-packages/dev-us-east-1-build
        du -sh dh-packages/dev-us-east-1-build
      shell: bash

    - run: |
        sls package --stage tst --region us-east-1 --deploymentBucketName dh-deployment-bucket-us-east-1-${{inputs.aws-account-tst}} --aws-target-account-id ${{inputs.aws-account-tst}} --old-env-id test --package dh-packages/tst-us-east-1-build
        du -sh dh-packages/tst-us-east-1-build
      shell: bash

    - run: |
        sls package --stage acc --region us-east-1 --deploymentBucketName dh-deployment-bucket-us-east-1-${{inputs.aws-account-acc}} --aws-target-account-id ${{inputs.aws-account-acc}} --old-env-id acceptance --package dh-packages/acc-us-east-1-build
        du -sh dh-packages/acc-us-east-1-build
      shell: bash

    - run: |
        sls package --stage prd --region us-east-1 --deploymentBucketName dh-deployment-bucket-us-east-1-${{inputs.aws-account-prd}} --aws-target-account-id ${{inputs.aws-account-prd}} --old-env-id production --package dh-packages/prd-us-east-1-build 
        du -sh dh-packages/prd-us-east-1-build
      shell: bash

    - run: |
        sls package --stage acc --region eu-west-1 --deploymentBucketName dh-deployment-bucket-eu-west-1-${{inputs.aws-account-acc}} --aws-target-account-id ${{inputs.aws-account-acc}} --old-env-id acceptance --package dh-packages/acc-eu-west-1-build
        du -sh dh-packages/acc-eu-west-1-build
      shell: bash

    - run: |
        sls package --stage prd --region eu-west-1 --deploymentBucketName dh-deployment-bucket-eu-west-1-${{inputs.aws-account-prd}} --aws-target-account-id ${{inputs.aws-account-prd}} --old-env-id production --package dh-packages/prd-eu-west-1-build
        du -sh dh-packages/prd-eu-west-1-build
      shell: bash

    - run: |
        tar cf packages.tar --exclude=**/requirements/* dh-packages
        du -sh packages.tar
      shell: bash
    # - run : aws s3 sync . s3://dh-package-repo-eu-west-1

    - uses: actions/upload-artifact@v2
      with:
        name: packages-artifact
        path: packages.tar
