name: "run-serverless-ci"
description: "Runs poetry install and runs the pytest"

inputs:
  code-artifact-account:
    required: true
    default: us-east-1
  code-artifact-domain:
    required: true
  role-to-assume:
    required: true

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1.1.0
      with:
        format: "YYYY_MM_DD"
    - uses: Gr1N/setup-poetry@v7

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{role-to-assume}}
        aws-region: us-east-1
    - run: |
        export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain  ${{code-artifact-domain}} --domain-owner ${{code-artifact-account}} --query authorizationToken --output text)
        poetry config http-basic.dh_pypi aws "${CODEARTIFACT_AUTH_TOKEN}"
    - uses: actions/cache@v2
      with:
        path: |
          poetry.lock
          .venv
        key: ${{ steps.date.outputs.time }}-${{hashFiles('pyprotect.toml')}}
    - uses: actions/cache@v2
      with:
        path: |
          ~/cache
        key: depcache
    - uses: actions/setup-node@v2
      with:
        node-version: '14'    
        cache: 'npm'
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: poetry install
    - run: npm install
    - run: npm install -g serverless
    
    - run: mkdir dh-packages
    - run: sls package --stage dev --region us-east-1 --package dh-packages/dev-us-build
          
    - run: sls package --stage tst --region us-east-1 --package dh-packages/tst-us-build
          
    - run: sls package --stage acc --region us-east-1 --package dh-packages/acc-us-build
    - run: sls package --stage prd --region us-east-1 --package dh-packages/prd-us-build 
    - run: sls package --stage acc --region eu-west-1 --package dh-packages/acc-eu-build
    - run: sls package --stage prd --region eu-west-1 --package dh-packages/prd-eu-build

    - run: tar cf packages.tar dh-packages
    # - run : aws s3 sync . s3://dh-package-repo-eu-west-1

    - uses: actions/packages
      with:
        name: packages-artifact
        path: packages.tar


    


