name: Reusable workflow example

on:
  workflow_call:
   

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Very Simple Hello World
        uses: phwes/simple_hello_world@v1
