name: Serverless CI/CD workflow

on:
  workflow_call:
    secrets:
      DEPLOYMENT_ROLE_DEV:
        required: true
      DEPLOYMENT_ROLE_TST:
        required: true
      DEPLOYMENT_ROLE_ACC:
        required: true
      DEPLOYMENT_ROLE_PRD:
        required: true
      AWS_ACCOUNT_DEV:
        required: true
      AWS_ACCOUNT_TST:
        required: true
      AWS_ACCOUNT_ACC:
        required: true
      AWS_ACCOUNT_PRD:
        required: true
jobs:
  ci:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dearhealth/shared-workflows/.github/actions/serverless-ci@python-3.11
        with:
         role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_DEV }}
         code-artifact-domain: dh-artifacts
         code-artifact-account: ${{ secrets.AWS_ACCOUNT_DEV }}
         aws-account-dev: ${{ secrets.AWS_ACCOUNT_DEV }}
         aws-account-tst: ${{ secrets.AWS_ACCOUNT_TST }}
         aws-account-acc: ${{ secrets.AWS_ACCOUNT_ACC }}
         aws-account-prd: ${{ secrets.AWS_ACCOUNT_PRD }}

  deploy-dev:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: ci
    steps:
        - uses: dearhealth/shared-workflows/.github/actions/serverless-deploy@main
          with:
            role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_DEV }}
            region: us-east-1
            env: dev
            old-env-id: develop
            aws-account-id: ${{ secrets.AWS_ACCOUNT_DEV }}
            dh-artifacts-aws-account-id: ${{ secrets.AWS_ACCOUNT_DEV }}
      
  deploy-tst:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: 'tst'
    needs: deploy-dev
    steps:
        - uses: dearhealth/shared-workflows/.github/actions/serverless-deploy@main
          with:
            role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_TST }}
            region: us-east-1
            env: tst
            old-env-id: test
            aws-account-id: ${{ secrets.AWS_ACCOUNT_TST }}
            dh-artifacts-aws-account-id: ${{ secrets.AWS_ACCOUNT_DEV }}
  deploy-acc-eu:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: 'acc-eu'
    needs: deploy-tst
    steps:
        - uses: dearhealth/shared-workflows/.github/actions/serverless-deploy@main
          with:
            role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ACC }}
            region: eu-west-1
            env: acc
            old-env-id: acceptance
            aws-account-id: ${{ secrets.AWS_ACCOUNT_ACC }}
            dh-artifacts-aws-account-id: ${{ secrets.AWS_ACCOUNT_DEV }}

  deploy-prd-eu:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: 'prd-eu'
    needs: deploy-acc-eu
    steps:
        - uses: dearhealth/shared-workflows/.github/actions/serverless-deploy@main
          with:
            role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_PRD }}
            region: eu-west-1
            env: prd
            old-env-id: production
            aws-account-id: ${{ secrets.AWS_ACCOUNT_PRD }}
            dh-artifacts-aws-account-id: ${{ secrets.AWS_ACCOUNT_DEV }}
