name: Serverless CI/CD workflow

on:
  workflow_call:
    secrets:
      DEPLOYMENT_ROLE_DEV:
        required: true
      DEPLOYMENT_ROLE_TST:
        required: true
      DEPLOYMENT_ROLE_ACC:
        required: true
      DEPLOYMENT_ROLE_PRD:
        required: true
      AWS_ACCOUNT_DEV:
        required: true
      AWS_ACCOUNT_TST:
        required: true
      AWS_ACCOUNT_ACC:
        required: true
      AWS_ACCOUNT_PRD:
        required: true
jobs:
  ci:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: dearhealth/shared-workflows/.github/actions/serverless-ci@main
        with:
         role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_DEV }}
         code-artifact-domain: dh-artifacts
         code-artifact-account: ${{ secrets.AWS_ACCOUNT_DEV }}
         
        
  
  deploy-dev:
    permissions:
      id-token: write
      contents: read
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: ci
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Start DynamoDB in GitHub Actions
      uses: rrainn/dynamodb-action@v2.0.1
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_DEV }}
          aws-region: us-east-1
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: packages-artifact
    - run: tar xvf packages.tar
      shell: bash
    - uses: actions/setup-node@v2
      with:
          node-version: '14'    
          cache: 'npm'
    - run: npm install
      shell: bash
    - run: npm install -g serverless@2
      shell: bash
    - run: sls deploy --stage dev --region us-east-1 --package dh-packages/${{inputs.env}}-${{inputs.region}}-build
      shell: bash

  deploy-tst:
    permissions:
      id-token: write
      contents: read
    runs-on: 'ubuntu-latest'
    environment: 'tst'
    needs: deploy-dev
    steps: 
       - uses: dearhealth/shared-workflows/.github/actions/serverless-deploy@main
      
         with:
           role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_TST }}
           region: us-east-1
           env: ${{ secrets.AWS_ACCOUNT_TST }}